### ISSUE TITLE
A fatal Javascript error occured

### ISSUE THREAD

**Issue by Meizwe** [bb010g/betterdiscordctl#17]
```
Ubuntu 18.04.1 LTS
Node: v8.10.0
Git version: 2.17.1

Snap --verbose:
name:      discord
summary:   All-in-one voice and text chat for gamers
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/discord/issues
license:   unset
description: |
  All-in-one voice and text chat for gamers that's free, secure, and
  works on both your desktop and phone.
commands:
  - discord
notes:               
  private:           false
  confinement:       strict
  devmode:           false
  jailmode:          false
  trymode:           false
  enabled:           true
  broken:            false
  ignore-validation: false
snap-id:      qHVefGEBezeuCeSfTND40uoUD6GRw8BO
tracking:     stable
refresh-date: yesterday at 21:31 EDT
channels:                     
  stable:    0.0.5 (73) 142MB -
  candidate: ↑                
  beta:      0.0.5 (73) 142MB -
  edge:      0.0.5 (73) 142MB -
installed:   0.0.5 (73) 142MB 

Window says:
Error: Cannot find module 'betterdiscord'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/snap/discord/73/usr/share/discord/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/miw/snap/discord/73/.config/discord/0.0.5/modules/discord_desktop_core/core/app/mainScreen.js:2:22)
    at Object.<anonymous> (/home/miw/snap/discord/73/.config/discord/0.0.5/modules/discord_desktop_core/core/app/mainScreen.js:609:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by ObserverOfTime** [comment]
What's the output of `betterdiscordctl reinstall --snap -v -v`?
And please enclose it within ` ``` `.

**Comment by Meizwe** [comment]
```
miw@q8D-AX370-K7:~$ betterdiscordctl reinstall --snap -v -v
VV: Checking /snap/discord/73/usr/share/discord
V: Using Discord at /snap/discord/73/usr/share/discord
V: Found modules in /home/miw/snap/discord/73/.config/discord/0.0.5/modules
Killing Discord processes...
V: Removing old core folder.
V: Unpacking core asar...
Updating asar...
V: Patching core entry...
Cloning https://github.com/rauenzi/BetterDiscordApp...
Cloning into '/home/miw/.local/share/betterdiscordctl/bd/0'...
remote: Counting objects: 6704, done.
Receiving objects:  29% (1975/6704), 4.84 MiB | 16.00 KiB/s
```

**Comment by ObserverOfTime** [comment]
This seems to be a network error. Your internet is probably too slow and is being timed out.
You can edit your `betterdiscordctl` file and add `--depth=1` to [line 489](../blob/aa3f7b3/betterdiscordctl#L489). That will make it run a shallow clone which should be faster.

**Comment by Meizwe** [comment]
where is the file in the betterdiscordctl folder?

**Comment by ObserverOfTime** [comment]
It's where you downloaded it. You can find it with `command -v betterdiscordctl`. You might need root privileges to edit it.

**Comment by Meizwe** [comment]
`git clone "$bd_repo" -b "$bd_repo_branch" --single-branch "$bd" --depth=1`, save & retry betterdiscordctl reinstall --snap -v -v ?

**Comment by ObserverOfTime** [comment]
Yep.
