### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by FFY00** [bb010g/betterdiscordctl#20]
I can't install betterdiscord anymore. I am running Linux and I've tried with and without `--global-asar`. Is there any kind of log I can provide?

**Comment by ObserverOfTime** [comment]
Yes, the output of the command you're running. Include the `-v -v` flag for extra verbosity.

**Comment by FFY00** [comment]
### With `--global-asar`
```
$ betterdiscordctl install --global-asar -b /usr/lib/BetterDiscordApp/ -v -v
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/anubis/.config/discord/0.0.5/modules
V: Unpacking core asar...
V: Patching core entry...
V: Linking core loader...
Installed. (Restart Discord if necessary.)
```

### Without `--global-asar`

```
$ betterdiscordctl install -b /usr/lib/BetterDiscordApp/ -v -v
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/anubis/.config/discord/0.0.5/modules
V: Unpacking core asar...
Updating asar...
V: Patching core entry...
V: Linking core loader...
Installed. (Restart Discord if necessary.)
```

On both, when string discord
```
Error: Cannot find module 'betterdiscord'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/discord/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/anubis/.config/discord/0.0.5/modules/discord_desktop_core/core/app/mainScreen.js:2:22)
    at Object.<anonymous> (/home/anubis/.config/discord/0.0.5/modules/discord_desktop_core/core/app/mainScreen.js:609:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by ObserverOfTime** [comment]
Run `reinstall` instead of `install` and post the output if it fails again.

**Comment by FFY00** [comment]
I ran `uninstall` before installing both but here it goes...

### With `--global-asar`
```
$ betterdiscordctl install --global-asar -b /usr/lib/BetterDiscordApp/ -v -v
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/anubis/.config/discord/0.0.5/modules
Killing Discord processes...
V: Removing old core folder.
V: Unpacking core asar...
V: Patching core entry...
V: Linking core loader...
Reinstalled.
```

### Without `--global-asar`
```

**Comment by ObserverOfTime** [comment]
Is the error still there when you start Discord?

**Comment by FFY00** [comment]
Yes.

**Comment by FFY00** [comment]
Okay, that worked. I cloned it one day ago so it's a bit weird that it wasn't working. Thanks for your help :grin:.

**Comment by ObserverOfTime** [comment]
BBD was updated many times yesterday due to a multitude of bugs.
