### ISSUE TITLE
Install Error: Unexpected token function SyntaxError when updating asar 

### ISSUE THREAD

**Issue by Infinidoge** [bb010g/betterdiscordctl#36]
Unsure if this is related to betterdiscordctl specifically or asar, but asking here since someone else might have had the same specific problem.

When installing BetterDiscord to Discord PTB using this command:
```
betterdiscordctl install -v -v -f PTB --scan /usr/share
```

i recieve the following output and the install fails:
```
VV: Scanning /usr/share
VV: Trying flavor 'PTB'
V: Using Discord at /usr/share/discord-ptb
V: Found modules in /root/.config/discordptb/0.0.15/modules
V: Unpacking core asar...
Updating asar...
/root/.local/share/betterdiscordctl/asar/node_modules/asar/lib/asar.js:29
module.exports.createPackage = async function (src, dest) {
                                     ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.local/share/betterdiscordctl/asar/node_modules/asar/bin/asar.js:2:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Some additional information:
betterdiscordctl  version 1.5.1
running on xenialpup 7.5
Discord PTB version `0.0.15` according to the install folder.

If any additional information is needed, let me know.

**Comment by ObserverOfTime** [comment]
What's your `node` version? My hunch is that it's outdated and doesn't support async functions.

**Comment by Infinidoge** [comment]
I am using node `v4.2.6`

**Comment by Infinidoge** [comment]
Looking into a bit more, I believe it is the same. How would i go about updating it?

**Comment by ObserverOfTime** [comment]
I recommend using a package from [NodeSource](https://github.com/nodesource/distributions#installation-instructions). You'll need at least v8.

**Comment by Infinidoge** [comment]
Ok i uninstalled the version mine came with so it is using the proper latest version. 

However, i got a different error (same command as originally):
```
VV: Scanning /usr/share
VV: Trying flavor 'PTB'
V: Using Discord at /usr/share/discord-ptb
V: Found modules in /root/.config/discordptb/0.0.15/modules
V: Unpacking core asar...
Updating asar...
/usr/local/bin/betterdiscordctl: /usr/bin/npm: /usr/bin/nodejs: bad interpreter: No such file or directory
Couldn't update /root/.local/share/betterdiscordctl/asar.
```
This i fixed by  symlinking the directory it looks for to my proper node directory.

Following this, I got this new error:
```
VV: Scanning /usr/share
VV: Trying flavor 'PTB'
V: Using Discord at /usr/share/discord-ptb
V: Found modules in /root/.config/discordptb/0.0.15/modules
V: Unpacking core asar...
Updating asar...
npm ERR! Linux 4.9.58
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "update"
npm ERR! node v12.2.0
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'ansi'
npm ERR! Require stack:
npm ERR! - /usr/share/npm/lib/ls.js
npm ERR! - /usr/share/npm/lib/install.js
npm ERR! - /usr/share/npm/lib/update.js
npm ERR! - /usr/share/npm/lib/npm.js
npm ERR! - /usr/share/npm/bin/npm-cli.js
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.local/share/betterdiscordctl/asar/npm-debug.log
Couldn't update /root/.local/share/betterdiscordctl/asar.
``` 

For this I uninstalled and reinstalled npm which fixed it, and running the command again worked.

Thank you for your help!
(Also now I know ever so slightly more about node.js)
