### ISSUE TITLE
Better Discord fails to fully load

### ISSUE THREAD

**Issue by JeremyStepp** [bb010g/betterdiscordctl#43]
On Discord no plugins load and no extra settings appear, but the betterdiscord icon does show up. I'm on Linux Mint 19 using the flatpak Discord. (I just tested and got the same error after a restart with the .deb download from the Discord website) The error I get after betterdiscord starts up is 
```
(node:4) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, watch '/home/jeremy/.var/app/com.discordapp.Discord/config/BetterDiscord/plugins'
    at FSWatcher.start (internal/fs/watchers.js:164:26)
    at Object.watch (fs.js:1232:11)
    at Object.watchContent (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:55:18798)
    at V2_SettingsPanel.initializeSettings (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:55:79707)
    at Core.init (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c268371144a5ac3dbeaa6b2af0aebcba055d10b5/js/main.min.js:4:580)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/app/bin/discord: line 9: kill: (3) - No such process
```

**Comment by ObserverOfTime** [comment]
You get the same `ENOSPC` error with the `deb` package?

**Comment by JeremyStepp** [comment]
Yes, but with the plugin folder in .config instead of the flatpak location.
`(node:19263) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, watch '/home/jeremy/.config/BetterDiscord/plugins'`

**Comment by ObserverOfTime** [comment]
What's the output of `df -h` and `df -i -h`?

**Comment by JeremyStepp** [comment]
df -h:
```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G   68K  7.8G   1% /dev
tmpfs           1.6G  3.1M  1.6G   1% /run
/dev/sdb2        48G   35G   11G  77% /
tmpfs           7.9G  1.6G  6.3G  20% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop0       90M   90M     0 100% /snap/core/6818
/dev/loop1       51M   51M     0 100% /snap/riseup-vpn/136
/dev/sda1       511M  6.1M  505M   2% /boot/efi
/dev/sda4       1.8T  637G  1.1T  38% /home
tmpfs           1.6G  628K  1.6G   1% /run/user/1000
/dev/sr0        527M  527M     0 100% /media/jeremy/HARRY_POTTER_US_3010
/dev/sdb1       409G  220G  169G  57% /media/jeremy/JcSsD
/dev/loop2       89M   89M     0 100% /snap/core/6964

```
df -i -h
```

Filesystem     Inodes IUsed IFree IUse% Mounted on
udev             2.0M   622  2.0M    1% /dev
tmpfs            2.0M  1.1K  2.0M    1% /run
/dev/sdb2        3.1M  718K  2.4M   24% /
tmpfs            2.0M  1.3K  2.0M    1% /dev/shm
tmpfs            2.0M     6  2.0M    1% /run/lock
tmpfs            2.0M    18  2.0M    1% /sys/fs/cgroup
/dev/loop0        13K   13K     0  100% /snap/core/6818
/dev/loop1        15K   15K     0  100% /snap/riseup-vpn/136
/dev/sda1           0     0     0     - /boot/efi
/dev/sda4        116M  3.4M  112M    3% /home
tmpfs            2.0M   380  2.0M    1% /run/user/1000
/dev/sr0            0     0     0     - /media/jeremy/HARRY_POTTER_US_3010
/dev/sdb1         27M   63K   26M    1% /media/jeremy/JcSsD
```

**Comment by ObserverOfTime** [comment]
Try increasing the [inotify watch limit](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached):
```sh
sudo tee -a /etc/sysctl.conf <<< fs.inotify.max_user_watches=16384
sudo sysctl -p
```

**Comment by JeremyStepp** [comment]
Thanks! I forgot to raise it after I installed nextcloud.
