### ISSUE TITLE
Discord not opening with betterdiscord installed

### ISSUE THREAD

**Issue by luni3359** [bb010g/betterdiscordctl#74]
I'm getting an error on startup that prevents Discord from opening.
```
Error: EACCES: permission denied, open '/home/user/.local/share/betterdiscordctl/bd/0/betterdiscord/config.json'
at Object.openSync (fs.js:447:3)
at Object.func (electron/js2c/asar.js:140:31)
at Object.func [as openSync] (electron/js2c/asar.js:140:31)
at Object.writeFileSync (fs.js:1206:35)
at Object.<anonymous> (/home/user/.local/share/betterdiscordctl/bd/0/betterdiscord/index.js:28:4)
at Module._compile (internal/modules/cjs/loader.js:880:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
at Module.load (internal/modules/cjs/loader.js:735:32)
at Module._load (internal/modules/cjs/loader.js:648:12)
at Module._load (electron/js2c/asar.js:717:26)
```
It doesn't seem like the file it's trying to load exists, here's the directory tree:
```
user@pc:~/.local/share/betterdiscord$  tree
.
└── custom
    └── notifications
        └── sounds
            ├── Oxygen-Im-Contact-In.ogg
            └── Oxygen-Im-Contact-Out.ogg

3 directories, 2 files
```

``sudo betterdiscordctl reinstall -v -v`` results:
```
VV: Scanning /opt
VV: Trying flavor ''
VV: Trying flavor 'canary'
VV: Trying flavor 'ptb'
VV: Scanning /usr/share
VV: Trying flavor ''
V: Using Discord at /usr/share/discord
V: Found modules in /home/user/.config/discord/0.0.10/modules
Killing Discord processes...
Discord killed (pid 32699)
Discord killed (pid 32702)
Discord killed (pid 32704)
Discord killed (pid 32728)
Discord killed (pid 32738)
Discord killed (pid 32753)
V: Removing old injector folder.
V: Linking BetterDiscord injector...
Reinstalled.
```

I ran ``sudo betterdiscordctl update`` and ``sudo betterdiscordctl upgrade`` a few times for good measure, before and after reinstalling. Uninstalling and installing produces the same error on startup. Discord opens without error when BD is uninstalled.

**Comment by ObserverOfTime** [comment]
Stop using sudo. Remove `~/.local/share/betterdiscordctl` and try again.

**Comment by luni3359** [comment]
Thank you!
